export enum ModePaiement {
  VIREMENT = 'VIREMENT BANCAIRE',
  CHEQUE = 'CHEQUE',
  ESPECES = 'ESPECES',
  CARTE = 'CARTE',
  PRELEVEMENT = 'PRELEVEMENT',
  TRAITE = 'TRAITE',
  COMPENSATION = 'COMPENSATION',
  CRYPTO = 'CRYPTO'
}