apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
  labels:
    app: angular-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
      - name: angular-frontend
        image: mariammseddi12/angular-frontend:latest
        ports:
        - containerPort: 80  # ← CHANGER 4200 → 80 (nginx)
        # ← SUPPRIMER command et args (nginx démarre automatiquement)

---
apiVersion: v1
kind: Service
metadata:
  name: angular-frontend
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared-ip"
spec:
  selector:
    app: angular-frontend
  ports:
  - port: 80
    targetPort: 4200  # ← CHANGER 4200 → 80 (nginx)
  type: LoadBalancer
  loadBalancerIP: 51.210.7.4
