apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
  labels:
    app: angular-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
      - name: angular-frontend
        image: mariammseddi12/angular-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-frontend
  annotations:
    metallb.universe.tf/address-pool: microservice-pool
    metallb.io/allow-shared-ip: "vps-shared-ip"
spec:
  selector:
    app: angular-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
