apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: mariammseddi12/gateway-service:latest
        ports:
        - containerPort: 9025
        env:
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://eureka-service:8761/eureka/"

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared-ip"
spec:
  selector:
    app: gateway-service
  ports:
  - port: 9025
    targetPort: 9025
  type: LoadBalancer
  loadBalancerIP: 51.210.7.4
